### ISSUE TITLE
Not Supported with Kubernetes v1.16.2

### ISSUE THREAD

**Issue by tiwarishrijan** [apache-spark-on-k8s/kubernetes-HDFS#81]
With Kubernetes `v1.16.2` on `CentOS Linux release 7.7.1908 (Core)` , Getting below Error : 

`Error: validation failed: [unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"]`

**Comment by ogni90** [comment]
I got the same problem on Kubernetes Version v1.16.3 using helm v3.0.2.

Any ideas on what causes this?

**Comment by ogni90** [comment]
This is fixed by #79

**Comment by tiwarishrijan** [comment]
> This is fixed by #79

Still not working. Compilation is done but datanode shows error.

**Comment by luisr103** [comment]
I just tried it using K8s version 1.17 and Helm version v3.0.2 on Ubuntu server 18.04.3 with the following results:

kube@kube-master:~/kubernetes-HDFS$ helm install sa-hdfs charts/hdfs-k8s --set tags.ha=false --set tags.simple=true --set global.namenodeHAEnabled=false --set hdfs-simple-namenode-k8s.nodeSelector.hdfs-namenode-selector=hdfs-namenode-0
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"]

it looks like the API for helm install changed because the suggested commands on your README will produce the following error:
kube@kube-master:~/kubernetes-HDFS$ helm install -n sa-hdfs charts/hdfs-k8s --set tags.ha=false --set tags.simple=true --set global.namenodeHAEnabled=false --set hdfs-simple-namenode-k8s.nodeSelector.hdfs-namenode-selector=hdfs-namenode-0
Error: must either provide a name or specify --generate-name

Any Suggestions?

**Comment by anilnokia** [comment]
I modified all files according to #79 but still same problem with K8 1.16 and Helm 3.2
 helm install -n my-hdfs charts/hdfs-k8s --generate-name
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"]

**Comment by L-maple** [comment]
I also came accross this problem in k8s 1.19.0, SO:
(1) What should I do for solving this problem fast?
(2) Will the maintainer will address this problem soon?
